-- Il est important que ces insert soit les premières dans la BDD sinon il y aura des erreurs avec les clées primaires

-- TOURNOIS

INSERT INTO TOURNOIS (JEU,DATEDEBUT,DATEFIN,PRIX) VALUES ('Overwatch','2018-09-27 16:00:00','2018-09-27 16:00:00',20000);

-- POULES

INSERT INTO POULES (NUMERO,ID_TOURNOI) VALUES (1,1);
INSERT INTO POULES (NUMERO,ID_TOURNOI) VALUES (2,1);
INSERT INTO POULES (NUMERO,ID_TOURNOI) VALUES (3,1);
INSERT INTO POULES (NUMERO,ID_TOURNOI) VALUES (4,1);
INSERT INTO POULES (NUMERO,ID_TOURNOI) VALUES (5,1);
INSERT INTO POULES (NUMERO,ID_TOURNOI) VALUES (6,1);
INSERT INTO POULES (NUMERO,ID_TOURNOI) VALUES (7,1);
INSERT INTO POULES (NUMERO,ID_TOURNOI) VALUES (8,1);

-- JOUEURS

INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,1,'J1');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,1,'J2');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,2,'J3');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,2,'J4');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,3,'J5');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,3,'J6');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,4,'J7');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,4,'J8');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,5,'J9');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,5,'J10');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,6,'J11');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,6,'J12');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,7,'J13');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,7,'J14');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,8,'J15');
INSERT INTO JOUEURS (ID_TOURNOI,ID_POULE,PSEUDO) VALUES (1,8,'J16');

-- PHASES_FINALES

INSERT INTO PHASES_FINALES (LIBELLE) VALUES ('QUART');
INSERT INTO PHASES_FINALES (LIBELLE) VALUES ('DEMI');
INSERT INTO PHASES_FINALES (LIBELLE) VALUES ('FINALE');

-- MATCHS POULE

INSERT INTO MATCHS (ID_TOURNOI,ID_POULE,DATE_HEURE) VALUES (1,1,'2018-09-27 16:00:00');
INSERT INTO MATCHS (ID_TOURNOI,ID_POULE,DATE_HEURE) VALUES (1,2,'2018-09-27 16:00:00');
INSERT INTO MATCHS (ID_TOURNOI,ID_POULE,DATE_HEURE) VALUES (1,3,'2018-09-27 16:00:00');
INSERT INTO MATCHS (ID_TOURNOI,ID_POULE,DATE_HEURE) VALUES (1,4,'2018-09-27 16:00:00');
INSERT INTO MATCHS (ID_TOURNOI,ID_POULE,DATE_HEURE) VALUES (1,5,'2018-09-27 16:00:00');
INSERT INTO MATCHS (ID_TOURNOI,ID_POULE,DATE_HEURE) VALUES (1,6,'2018-09-27 16:00:00');
INSERT INTO MATCHS (ID_TOURNOI,ID_POULE,DATE_HEURE) VALUES (1,7,'2018-09-27 16:00:00');
INSERT INTO MATCHS (ID_TOURNOI,ID_POULE,DATE_HEURE) VALUES (1,8,'2018-09-27 16:00:00');

-- MATCHS QUARTS

INSERT INTO MATCHS (ID_TOURNOI,TYPE_MATCH,ID_PHASE,DATE_HEURE) VALUES (1,'o',1,'2018-09-27 16:00:00');
INSERT INTO MATCHS (ID_TOURNOI,TYPE_MATCH,ID_PHASE,DATE_HEURE) VALUES (1,'o',1,'2018-09-27 16:00:00');
INSERT INTO MATCHS (ID_TOURNOI,TYPE_MATCH,ID_PHASE,DATE_HEURE) VALUES (1,'o',1,'2018-09-27 16:00:00');
INSERT INTO MATCHS (ID_TOURNOI,TYPE_MATCH,ID_PHASE,DATE_HEURE) VALUES (1,'o',1,'2018-09-27 16:00:00');

-- MATCHS DEMI

INSERT INTO MATCHS (ID_TOURNOI,TYPE_MATCH,ID_PHASE,DATE_HEURE) VALUES (1,'o',2,'2018-09-27 16:00:00');
INSERT INTO MATCHS (ID_TOURNOI,TYPE_MATCH,ID_PHASE,DATE_HEURE) VALUES (1,'o',2,'2018-09-27 16:00:00');

-- MATCHS FINALE

INSERT INTO MATCHS (ID_TOURNOI,TYPE_MATCH,ID_PHASE,DATE_HEURE) VALUES (1,'o',3,'2018-09-27 16:00:00');

-- SCORE DES MATCHS DE POULE

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (1,1,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (2,1,'1000');

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (3,2,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (4,2,'1000');

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (5,3,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (6,3,'1000');

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (7,4,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (8,4,'1000');

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (9,5,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (10,5,'1000');

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (11,6,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (12,6,'1000');

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (13,7,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (14,7,'1000');

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (15,8,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (16,8,'1000');

-- SCORE DES MATCHS DE QUART

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (1,9,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (3,9,'1000');

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (5,10,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (7,10,'1000');

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (9,11,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (11,11,'1000');

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (14,12,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (16,12,'1000');

-- SCORE DES MATCHS DE DEMI

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (1,13,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (5,13,'1000');

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (9,14,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (16,14,'1000');

-- SCORE DU MATCH DE FINALE

INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (5,15,'1000');
INSERT INTO SCORES (ID_JOUEUR,ID_MATCH,SCORE) VALUES (16,15,'1000');